In [6]:
import pandas as pd
import numpy as np

In [16]:
myxls = pd.ExcelFile('TincyCo.xlsx')

In [17]:
myxls.sheet_names

['SKU Master', 'Store 312', 'Store 323', 'Store 415', 'Store 521', 'Store 632']

In [22]:
SKU_Master = pd.read_excel('TincyCo.xlsx',sheet_name='SKU Master')
Store_312 = pd.read_excel('TincyCo.xlsx',sheet_name='Store 312')
Store_323 = pd.read_excel('TincyCo.xlsx',sheet_name='Store 323')
Store_415 = pd.read_excel('TincyCo.xlsx',sheet_name='Store 415')
Store_521 = pd.read_excel('TincyCo.xlsx',sheet_name='Store 521')
Store_632= pd.read_excel('TincyCo.xlsx',sheet_name='Store 632')

In [24]:
Store_632.head()

   DB_ID         SKU  Store       Date Unit Sales  Dollar Sales
0  95610  7312455520    632 2004-08-19          1         22.99
1  95611  7312455520    632 2004-08-20          2         45.98
2  95612  7312455520    632 2004-08-21          2         51.98
3  95613  7312455520    632 2004-08-27          2         45.98
4  95614  7312455520    632 2004-08-28          2         51.98

In [23]:
SKU_Master.head()

,Department,Class,Style,Color,SKU,Cost,Price,Vendor
0,800.0,5.0,20.0,2.0,8000520021,7.5,9.99,MA Excellent Products
1,800.0,4.0,51.0,11.0,8000451112,9.0,12.99,MA Excellent Products
2,731.0,24.0,55.0,52.0,7312455520,25.0,31.99,MA Excellent Products
3,731.0,24.0,55.0,53.0,7312455530,14.5,22.99,GA General Wholesales
4,5001.0,201.0,12.0,4.0,50012011240,2.5,7.99,China Imports

In [ ]:
SKU_Master.columns

Index(['DB_ID', 'SKU', 'Store', 'Date', 'Unit Sales', 'Dollar Sales'], dtype='str')

In [27]:
Store_521.columns

Index(['DB_ID', 'SKU', 'Store', 'Date', 'Unit Sales', 'Dollar Sales'], dtype='str')

In [28]:
Store_632.columns

Index(['DB_ID', 'SKU', 'Store', 'Date', 'Unit Sales', 'Dollar Sales'], dtype='str')

In [29]:
Store_415.columns

Index(['DB_ID', 'SKU', 'Store', 'Date', 'Unit Sales', 'Dollar Sales'], dtype='str')

In [30]:
Store_323.columns

Index(['DB_ID', 'SKU', 'Store', 'Date', 'Unit Sales', 'Dollar Sales'], dtype='str')

In [26]:
Store_312.columns

Index(['DB_ID', 'SKU', 'Store', 'Date', 'Unit Sales', 'Dollar Sales'], dtype='str')

In [35]:
all_stores = pd.concat([
    Store_521,Store_632,Store_312,Store_323,Store_415

]
  ,axis=0                     )
all_stores = all_stores.reset_index(drop=True)

all_stores.head()
all_stores.shape

(19278, 6)

In [43]:
all_stores['SKU'] = all_stores['SKU'].astype(str)
all_stores[all_stores['SKU'].str.contains('\\*')]
all_stores['SKU'] = all_stores['SKU'].str.replace('\\*' ,'0' ,regex=True)

In [44]:
all_stores[all_stores['SKU'].str.contains('\\*')]

Empty DataFrame
Columns: [DB_ID, SKU, Store, Date, Unit Sales, Dollar Sales]
Index: []

In [ ]:
all_stores['Unit Sales'].unique()

Unit Sales
1           3822
2           3588
3           2807
4           2070
5           1421
            ...
83             1
105            1
-A45%0 7       1
-A45%0 9       1
#0 5           1
Name: count, Length: 119, dtype: int64

In [47]:
all_stores['Unit Sales'].value_counts(dropna=False)

Unit Sales
1           3822
2           3588
3           2807
4           2070
5           1421
            ...
83             1
105            1
-A45%0 7       1
-A45%0 9       1
#0 5           1
Name: count, Length: 119, dtype: int64

In [49]:
all_stores['Unit Sales'] = all_stores['Unit Sales'] .astype(str)

wrong_unit_sales = all_stores[all_stores['Unit Sales'].str.isnumeric()==False]
wrong_unit_sales

       DB_ID          SKU  Store       Date Unit Sales  Dollar Sales
1899   34606  50012011240    521 2004-09-29        NaN           NaN
1920   34627  50012011240    521 2004-10-26        NaN           NaN
1944   34651  50012011240    521 2004-11-23        NaN           NaN
1971   34678  50012011240    521 2004-12-25       #0 1           NaN
1976   34683  50012011240    521 2005-01-01         -1         -7.99
...      ...          ...    ...        ...        ...           ...
19189  83978  50012011341    415 2006-05-19        NaN           NaN
19190  83979  50012011341    415 2006-05-20        NaN           NaN
19198  83987  50012011341    415 2006-05-31        NaN           NaN
19228  84017  50012011341    415 2006-07-10        NaN           NaN
19231  84020  50012011341    415 2006-07-14        NaN           NaN

[455 rows x 6 columns]

In [50]:
all_stores['Unit Sales'].value_counts(dropna=False).tail(50)

Unit Sales
63          7
-A45%0 4    6
40000       6
-A45%0 5    6
30000       6
-5          6
+9-A0       6
68          6
72          6
67          6
50000       6
47          5
55          5
65          5
60          5
66          5
53          5
78          5
69          5
71          5
#0 2        5
#0 4        4
+9-A3       4
48          4
74          4
45          4
-6          4
-A45%0 1    4
75          3
70          3
20000       3
60000       3
#0 0        3
-A45%0 6    2
76          2
64          2
73          2
81          2
90000       1
-9          1
82          1
80          1
88          1
91          1
79          1
83          1
105         1
-A45%0 7    1
-A45%0 9    1
#0 5        1
Name: count, dtype: int64

In [51]:
wrong_unit_sales['Unit Sales'].value_counts(dropna=False)

Unit Sales
NaN         261
-2           24
-1           22
-3           19
+9-A1        16
-A45%0 2     13
-4           10
-A45%0 3     10
+9-A2        10
#0 1          8
#0 3          8
-A45%0 4      6
-A45%0 5      6
-5            6
+9-A0         6
#0 2          5
#0 4          4
+9-A3         4
-6            4
-A45%0 1      4
#0 0          3
-A45%0 6      2
-9            1
-A45%0 7      1
-A45%0 9      1
#0 5          1
Name: count, dtype: int64

In [53]:
all_stores['Unit Sales'] = all_stores['Unit Sales'].replace({
    '#0 0': '0',
    '#0 1': '1',
    '#0 2': '2',
    '#0 3': '3',
    '#0 4': '4',
    '#0 5': '5',

    '-A45%0 1': '1',
    '-A45%0 2': '2',
    '-A45%0 3': '3',
    '-A45%0 4': '4',
    '-A45%0 5': '5',
    '-A45%0 6': '6',
    '-A45%0 7': '7',
    '-A45%0 9': '9',

    '+9-A0': '90',
    '+9-A1': '91',
    '+9-A2': '92',
    '+9-A3': '93',

    '30000': '3',
    '40000': '4',
    '50000': '5'
})


all_stores['Unit Sales'].value_counts(dropna=False)

Unit Sales
1      3834
2      3606
3      2831
4      2086
5      1434
       ...
80        1
88        1
79        1
83        1
105       1
Name: count, Length: 101, dtype: int64

In [54]:
all_stores['Unit Sales'] = all_stores['Unit Sales'].replace({'nan': np.nan, 'NaN' :np.nan})
all_stores['Unit Sales'] = all_stores['Unit Sales'].astype(float)

In [ ]:
all_stores.shape

dtype('float64')